gitGraph
    commit
    branch Engineers
    checkout Engineers
    commit
    commit
    checkout main
    merge Engineers
    commit
    branch Scientists
    checkout Scientists
    commit
    commit
    checkout main
    merge Scientists
    commit
    branch Miners
    checkout Miners
    commit
    branch Bridge
    checkout Bridge
    commit